### ISSUE TITLE
Actividad 6

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-de-melissa#2]
[ReporteDiagrama3.0-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-de-melissa/files/9666295/ReporteDiagrama3.0-1.pdf)

**Comment by Valentiin01** [comment]
calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
